version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app
      - /opt:/opt
    depends_on:
      - db
    env_file:
      - ./app/.env
    networks:
      - db_network
      - web_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5555:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - db_network

  lua:
    image: "openresty/openresty:alpine"
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx:/usr/local/openresty/nginx/conf/
      - ./nginx/logs:/usr/local/openresty/nginx/logs/
      - ./lua:/usr/local/openresty/lua
    networks:
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres:
